apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: system
  source:
    repoURL: "https://github.com/a19simma/argocd-cluster-bootstrap"
    path: system/monitoring/Chart
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
