loki-stack:
  loki:
    readinessProbe:
      initialDelaySeconds: 120
    fullnameOverride: monitoring-stack-loki
  promtail:
    config:
      clients:
        - url: http://monitoring-stack-loki:3100/loki/api/v1/push

kube-prometheus-stack:
  grafana:
    persistence:
      enabled: true
    adminUser: ~
    adminPassword: ~
    admin:
      existingSecret: "grafana-admin-secret"
    grafana.ini:
      feature_toggles:
        publicDashboards: "true"
