apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc-clone
  namespace: harbor
spec:
  storageClassName: ceph-filesystem

  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi