traefik:
  globalArguments:
    - "--global.sendanonymoususage=false"
    - "--global.checknewversion=false"

  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"
    - "--log.level=INFO"

  deployment:
    enabled: true
    replicas: 2
    annotations: {}
    podAnnotations: {}
    additionalContainers: []
    initContainers: []

  ports:
    web:
      redirectTo: websecure
    websecure:
      tls:
        enabled: true
    websecure-ssh:
      port: 2096
      expose: true
      exposedPort: 2096
      protocol: TCP

  ingressRoute:
    dashboard:
      enabled: false

  providers:
    kubernetesCRD:
      enabled: true
      ingressClass: traefik-external
      allowExternalNameServices: true
    kubernetesIngress:
      enabled: true
      allowExternalNameServices: true
      publishedService:
        enabled: false

  rbac:
    enabled: true

  service:
    enabled: true
    type: LoadBalancer
    annotations: {}
    labels: {}
    spec:
      loadBalancerIP: 192.168.3.0 # this should be an IP in the MetalLB range
    loadBalancerSourceRanges: []
    externalIPs: []
