apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
  labels:
    backup: "true"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: gitea-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-pv
  labels:
    backup: "true"
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.4
    path: "/mnt/default/gitea"
  mountOptions:
    - nfsvers=4.2