apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitea
  namespace: git
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`git.simonmalm.com`)
      kind: Rule
      services:
        - name: gitea-http
          port: 3000
    - match: Host(`git.local.simonmalm.com`)
      kind: Rule
      services:
        - name: gitea-http
          port: 3000

  tls:
    secretName: simonmalm-com-tls
