apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgB0imRFH4jeHZjyhHDHTWBI/ETygukKQVywXBlfb2lGsSAAQgeTqE7dcb8wyz6junxuxNV2wL++usAhLw/wDkXp2DmwvfYT9cl5zEql8zkKLrWJTW96u2nnAliZOhqt1OEiXNxvNkAVDixATbGh6QCi1jMbDgaMHEA2gJ1DLpznP5XFYmql3Dy3dKVW01BCeBAOgd0Vpwig1sdJ+g345Lrgire+axmXSY1ggkfb5Sz6xwYN9yN+zdPgeXu8XRILAIM2F+cprOq327aC1kzPg/KBJiDMIKEHutl2glFlVvxdQdoWhIu+NhVS3AvIG4gMDjxQMeqbncIvfyywJ3zuvfuGmo96t2WvKDM5fr/flurTEosvXANTy+iMCgw53mBTaPrmJNKAbFI5nrRWeqxYkpMWvE10GUkG3mbhRVf3fS9G7ZZO7dPDydo/V26YHrV/PPjlbKrwNi+/vL6H7LNxDzarz8FHXunqT87GOKO+jhbDfyaSKSf53p56g4+0MgDNmSjziEMw3ncRNmkhd9WcgN6LswRvFSJi0OL0XO+Wvkuwvi57mCEbQj0sM8DIgTH5P6TPunwydIWkbXUcyorCdkZ8qj1wnM/RBGAesONfS0YabP87KDj0EgKWBi4v1PG96DlLDgj/juDfGvI6lfuVq19P49MsmNAfuZOVw+ACvEVv781cy9hAg662Yved/LpkL5e05jsu7mFaCcsJLNdRYA/3VxculA==
    username: AgA7vHLN/YL5A6YhNjCcHbkbsox8bcUTDsAIwO4Cv4B3uxElNXYjWfMpFfjhIM6nGFx9fyJCRx0hyem7YY2isns3SU3rArTnh8XEQvlLJMXXzsDSeyJF4913W3x0ZmXDVhihmrpviw0FwWacCiZ847mOv1Xw9q5N/0+oGdvTvgLYTLvIQWA3LZe00tNa21tE9tdaJXZ2CwdwemlTkn5UJoTyFXCHGLymdyAGDRW2FTgOg+9UU3MdQyOzyxTEGMLpSBrQw+ZPEN/KM9NKAakgQHtqT4lU0corqEg99Aa1G9eYwrFCkf5v0K2olFXYFVR0dPTgJhF0HJXeg3xHt5mRlA0O9OS20BpG/hwRceM/jQJ0dJ+W5TBiiNG7//MgrVkUvE7TAHxsC/503dzj0hppUo+U9QHE3V9Ro8uQSVPSPnAwLrqkA+RXfdWVCGs8k0bRd94gc2ZnL9kdFNIiFqEWN1pq9Ciq8LFbvNE0pIpTmfOW3rqgXexA1gPmNjQ42LEqustVJ22GsxzjTi/nYPv/S3BKR0UVVnjxvMzEJz+YQct/+C7fUIFiG1w/jUaP/VHiBBNnF1lBk4+u86UNx34iBJDAEwwkOX5Q5dSQuDxvqgRk/jcN/PrN5QvVHF/nDSVBITXHE/bXIo2+z+dcKh+W0EH/ccgHXL2uMGoTALevfDBWVVMV9bb3Xo+aVLYPfuQdPXhwgvdAvQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
    type: Opaque
