apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgBE3PTzKaEda2nsc0iET+W42rZ8gvGRAU/GiD+0IG8XrwVgdKUSe6DdVY8POV5sW2XS4zGIpheAcZmagDxTonCr4M+BcWtGQ7l39C667EWwmEze1G5EbFMHgoyPa/a1W8sbGZGlgNVQdKm0FWsWuBUFjbQDM5eioYp9M+MkMPKiaMUAi+Ywkd+SOVNRD4N4HXnbXxTDvU1qkqA1JBYmN/mA/FSbAVLULZb5Nn8xRDBpyaqO82u3CqBhC6f4zd8iGmbJXdYqWQLMmQkIFpFHOtkZXl7B8jrOSetotAoePoxjMNzdDMfoPT7q2Mfzx3wR/LopWwwHoIVE4ouMxdEaV+h9dAW/yrtPEp7j/8p7mcPpeF+IdMibgDy86tNoOiDqsVSaHELKxHz/F6iw/N90JJ7YwCLfteG4fWgiOFgoI5lXghOPSvpUpaOUuSsicKkiV4iFuHD0sSXDzaaGtCqq5LsF65167gckOEV6mhXM+VEhvig31G0puWuANKkThAxVMKTziXT9QmSe2wWa338FDL89DjbEJ2tfXn3bqBODgib+QRwEzhIHaTGtWWf20xJhspm12wNb2DL266V31ZG9F8CsOliIa5fhTu/QtC6Ne24NSH6VKlwjUci5mv/KQ3F18EHWp2Sv4RbJEY4xTntKTZFSjjnjYAfQVI/aQy4pmUFTKvDYft89NyCa1xU6hiR/bPOqWUh+2j33dWaYsiUkp3/7wT41r
    username: AgBVkSQxMX/Lqsz97/hBGzsW7bpdg9ola1Tj6j5/EnXdSHWB8UD4Orv05xXyXlpQBksISokt1VTB12xbw8m8mLfAYYItyctMzQeNMu2Pk17qkvc+4Aauz3d3ovtCdvoh+nAotgNzB5j9zhsOTAR8DONBrkGq8/5Md/eh8leTva96ROE5uxI2Ag3Lt2G+IjJ5WH4KJ26pk+fkUuTlfZyjwYgmpPcNcIJadoTeTQykXBw2VlKpaDIXLu9s/gjvQ1mVwVLd8WUbdeVqi+3SN1p7iNdyD2d39M6Fyg0/pKN1wpFaxQpzP03/VFBGsUIF4wuyIJl5Tf0nImni3TUDm6FH8jxUSFo6vkMWS7VtNXD50b1oXrSfeZi9A22MJCGGMAmkLRAIf7EGPGqfavFznFGDKX/BhquPdK/h6AFiiGDD0ZnxpO3abORVPl0Au0LayVTHos4PSAWgE/C6BokZiZvwinihu8wxEzWcaEkIWoRUqzoDnjGbW8Y2ryzzWa1epoZPHFX9ciqfjPptbs1ssDXMLPnsUY+RnAEXlCU9LX7iCidwVLdhdZmUlj0J4ouNp8r8Q/HteiLpVHJrbML/PdrUNfzV6JUaaMRiPXu/SceFeXw62sxkIBP5YBsrErwFTsI74gzoMdq6Vl9Y4n6SMOSPprFS6SAz5ZMtg4ZcqiRzMKyVt1p/zzAVmUy8DU068gMi0eifZoyuwKjwyKljnA==
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
    type: Opaque
