apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgBalpqFYxdLtUwzO4vDIdq+8F6QkYbu5wVpSSfJjZXiV45aCzJDNSi3FotH7s4wxvUjmstQYvBm7I6o8MlQCUWDTl4KL9F4LcLdZTxaMF4KARHRsJ7S0JbSoNgvrP4PQ7CdjbsyTrFsQpv29f65yIqF6Ombj5W6IHWsIW3QOnqQZh6wg/Ag3jYiePvzf+qmBDsMYKOM70GZB5pbLMOlZ4qlJK0g3cdJlZGQWzlfgshfHPqQWIJbDHEBhiBXYgX3aduc24HGGBBfKZuO1Q5q+nOfjlOk7Etcf6N0LYXcwuqu8l8DIsN8R1NAx+6etjZjUn8Tg6k0XeS369TuGxwMB0ED3eykUqiAoH0J8RFMtf3QRQpM5ofOxa5rgxel0RKYAoc3Q3b0vKiP8sCE8+BcwAvL7MlhD5f8CtASulnIEDh6QW4ERVdSIm9ymHHJDJS2NRXhgIZTV8DC06oY7mtC3oROoVfx6HeDXjj4wZDOBr6eJXJpzyx2UJjT7kMTsM0+FCdDR93Gltjku5aB9eOvEaCHchrHZR4q5r50fRPsNshNN0Wsf43eqMKrFd7RW21KNijsAmYxNa0jzBNXStdoLSQ5eUfexp7/GAc8U5hAKlVjlMjWprkztTLUDSIM8bOs3UX+7V1Ua5Qo+0p1wDrq/5fHmbliG9i66OgnCR/8ogEBnijUGCxSA3ac00u3T5QB5XS6bqQHxJyhvYlF5RNNF7jm3ikO
    username: AgBX/hd8xcfr8G/FeKlExUPDN4tSgTfsRrl44VY4ONgehjlbK0SlkLtKMmoMfr95VCyjWlE1v+0UxjRMLN4Yt8eaz/cpG/Mi6Z4UkyXw93XfgFv/XM0xZMvOrJdpmtVrjwiJqVjgn5UBNfixYbBPdVDbHMrn8PiT4VRbwnMhEcQ8mu+y4315pGmmgUUUaHP6CGZE2z+WIr56JuFmBmymsCyd+l8pZeknhgpeLO6csAClMwK6q/x4A32V+YClmFGsoRZ1HDQNRTZSAFOHlGzK8b9wdu5uA4p7qcCNPjP/whFRLYEJaBch9/TfdgPXYpqV4YUZW4vt1lBHL3tAOptGld0RDBoWI85ShV56HlWjigClu8lqHKAqcOjfIKK6JiiusJ0zfIcOuJzixA+1KlZuKJitjT95i74hb2RgU65PQ97clttj1Flrne7tOZAP8/7wozjFBV4+ZdA7991Unh/vamdqCVZkbenZO70j+p1re8pABBsCzTnRh1kKEAahOGxkLjYFX9SspZEvFqpotYi8NnWGuo9c3lYNg6ER/WwjG6aLggN9x9MiVbpRm3V81vtVbp0zAonnKQfOsHnGu4Zgwc6hndI52Ve0g/lHIq5NY3EJsO16+XNQ4I2Auxdug0t5RsDph7C95S7vTo0KEdSGOvuWJrCXw6j3aRRcVNvOeRggO9ZjK4Ivg25R/7Br8yZ/085puAqo5Q==
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
    type: Opaque
