apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgBkxhf4s10BnK6wV5mBC5d/I8wUKZuC2t7xFX61llnUk3baa7Vzc3CeRq5smfFLZR8q2VpVyChWhvAUx4Nrmz5uJYIzdu8L6WH7+a44lR4gnzv6uCC9PHlCyf1oqnnpTvGKYESryENKNaLHVBrz0EP6ywreX24p0a4j8o0orIxhrq8hAAbUdjVYVJJ2r2UsVSjgzGRqqNfRDxz3IwVHGzy2emSW2OfGdT2sUV08xXpuP5nWz7hwBvFEVoXdbRuvOGa82Zhef9HVu/tTXneINTmLsB/dBJix4fxi7Dk1Kva1zVN3Z+48EfisafxA9FL6bhaY9goCz765oYSnsY21Cp1h7r2AH3z6EmS3GII/yuFL2rrxjnftDW06bjkzTVT22Sl9/H+bAT6z4bE1xNwoJ5ldS1BuUUA10Vw7PIsYQ4bQfzlYzqRzwNJb+M6hvd2p7NAy9PYo8fQA08kevNo4MBz04WnIoY9F5WJMRXe9NvHMACxy4rSBbPcZZ8py7Fs8xaiKg6PEr08X7BB08p3C2MJ8VWlSJHpVt1+DvOUTtsrbHWj8ycZvsOD7AOieW34lZlf4EKJE3yFJnHoUZ6JifR/JAJETEuO9SaoC4PBGDGMhZuinyy+KL4IreGwcocCxEDEadedjkzt5qGIQM369/JW98ZajH+b4DY1J6MQpnt3lVWk6xXCvW4WD0ZtOqxmCb1o=
    username: AgAs5u3Mzkc1L3LJoRD0JNhlcnke8Ho5YjaQYX4NOTNn1ogJT4ZVUaCvNCRlk4hGedJOal7rKm8mcTB+9kVH4a1IsvJcHDdSnU85th7p2U+XMeirES0LJ0kRZw60JnpH3wG9E8aqqExkJkICbmf5mIWKxYPE8gmN5KEkM9YAE5VjKv7U8Xi0nUod/GrWMHJGRr2RmuqlrAUU6/xGKI85ut4yPopYjBCsNGncwBpJVyLQFzzBWLYtA7z/2/WGyMX2Tx06WcceOxFj611ZMqfvMHp4aOa1JnzyjfZH3y7Tpr1hxSPfRR+2AqTxg4in0NXkF2qGs2bJdxEQINk6ydn8Ybhh2QqpTUcJicOI/5f8okH5LyAGrBbExKFWOOOF9w7CaKTOWvW74Bs4A9SmNQWZevxHblo4PJXzeH32G5i2MOHJm3/qKdOnkQnlLEHaQHIPdLfFEE7yan2q61AGgwSHEM9GeoMkJkuRZP7t0YgjT9s95tVI2xKGSor+zyVm58mBaMJuAMHtP8iimYBnOfE2PE9QOHlqxEhNkXgCPgdLWajxLkOP+qYQDe7GdMsPYjbdk66s3efhqJgYCvPZy8gYGyFGveavmCBHV3CavvvxrKmu5CWbopGs7xk/KrjcwgUzwHV4/4WOaSpBoW6ANiXg5ljVKxXY1F3RB1yaPfDKWcA/fDsJQW3lQnOPsz8Cl1xn415REWyMWxpLresBTw==
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
    type: Opaque
