apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgAhlJ+OR6eSdsrG9WkHjYlOF+opqDB+z/BL+sIWruZUXlTWtN0BxUHDh91B/4uJgucA7T7xo5PLXSs0BJ9uLQJIyRUpoc4+xklollB9Oq1otWKKS0B7V9MS93uRCMCN+3wcA0QRvYjLvI8WoX7EF/72V00TBG89JSZBfzaZsIqlUx/Pv1GYrGMxBcqZlpDZyrykoVTg2azYdYT02nfuVkBTa17RveF3ODQ0gD6paDXMYdi72wp6bSYG5oBqWwQW3frNVHH/VcW2+dvoqwYRSPQ0YBxPUPKQZC4iHUBGChi6XQDYNOo+HABf9z8k7jo8pHapTlrcn2iqjdy4p9pLm9eezc8w9qqgzxi+MzOA29+RSAmaPGGT4LZXypar8eGk0kllG8no497h+CVB8tdGsTyT1jrYcDc5WdySFmg0zoPA6yx560rqDJAh0eyn6g4fuOLLh4XJWFbP1O7jF7fteATE9O6tB4NijnpTXse5JUY31f0ZZPhghzasFE8TFy/7l9EpXxwVkPGJK3ql4/+zRczdGFdQy2arKwX++i6OugW1SVtwh3PL2hiAeQlzUaZX1SAm+IDrAQ9czIyA+QNRwHEH8hLiwSzcDYc2PdHhh24+mRoc04b5PTwpVeYfn8KL/A5mbsf79GqgMYSDEZxk2dzLSMomXWUm+5/cV7al6BmFaxMpert++30AF0ax/pg43TflUY9Uz4QJ2BeYQZLDcb+OoUV6
    user: AgDCZJ4ZEu8qVLN2BngP6FQdUgRpmGXKYCWFjhBSVaJ7GvqRSfpUp/8iy+ZPPvykWCibnQffExMpXIYF8QJiavcHTKlmLhlfao6KdEg1WwKLLyYscqbs09fsNBL2fNxFzd10981PqD/XNpWDVkOGDIBYehrFJ8AC7rpS0ryxYMSCusxbMOD6HH6Q6ihBRDXBPNIKfhFWy0khMXOnb0Vh0IHlOXPqu5K/xMyLM/oqdxYnrff5ebXwsXW7cDWzNcmNXV6GZCA//bpr6uMHIpA5vI+iuI5EWzGPjl6gfMzrsaH5zducdJHAtWa2jMeUR6par1EvGZYlJnI5VUDJHSSE3v/ojxUCoY+GJSUMsUzWp/eWnU0g4EYk5VCwigcrjKDwi+l80FJ5FRYRUhXaJ5UbXVdofyguFszsDCx5J35+jvMnomS1Le5lTWSvi/auYjspGgZ5F8b/VltUHZhsStjxp7OlxcTsU7kcLWmSWmxaw9SKnq6ZvFNHxdVogMvquAFK7KNOisPQz/13VZQeOWwXHUD3rzB/7YEbuA0rkUNUM/CzEsdjYns1MbMLlrqgNMgQ4arZ8OpGdA8JKpKw1/zCa0NNLCPae4PSXvhwQLzzZzv5HGs5cMVZ4c2rGt/QlH015Lajr8PfcrR4IqIna4aNPvqT7SJ7+6tdnNfhMbhJsfbYUcUCQ9w7GDVfkee8Jvrbc+82RFiSxZdH7jwr2Q==
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
    type: Opaque

