apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgB0imRFH4jeHZjyhHDHTWBI/ETygukKQVywXBlfb2lGsSAAQgeTqE7dcb8wyz6junxuxNV2wL++usAhLw/wDkXp2DmwvfYT9cl5zEql8zkKLrWJTW96u2nnAliZOhqt1OEiXNxvNkAVDixATbGh6QCi1jMbDgaMHEA2gJ1DLpznP5XFYmql3Dy3dKVW01BCeBAOgd0Vpwig1sdJ+g345Lrgire+axmXSY1ggkfb5Sz6xwYN9yN+zdPgeXu8XRILAIM2F+cprOq327aC1kzPg/KBJiDMIKEHutl2glFlVvxdQdoWhIu+NhVS3AvIG4gMDjxQMeqbncIvfyywJ3zuvfuGmo96t2WvKDM5fr/flurTEosvXANTy+iMCgw53mBTaPrmJNKAbFI5nrRWeqxYkpMWvE10GUkG3mbhRVf3fS9G7ZZO7dPDydo/V26YHrV/PPjlbKrwNi+/vL6H7LNxDzarz8FHXunqT87GOKO+jhbDfyaSKSf53p56g4+0MgDNmSjziEMw3ncRNmkhd9WcgN6LswRvFSJi0OL0XO+Wvkuwvi57mCEbQj0sM8DIgTH5P6TPunwydIWkbXUcyorCdkZ8qj1wnM/RBGAesONfS0YabP87KDj0EgKWBi4v1PG96DlLDgj/juDfGvI6lfuVq19P49MsmNAfuZOVw+ACvEVv781cy9hAg662Yved/LpkL5e05jsu7mFaCcsJLNdRYA/3VxculA==
    username: AgBlMwpwDInuL2CVyPfC6Gvq3IFdNE5pPel8Ef58QvEuH+1+VLnYahY0zMf+Nz/7lKfB3azK76t7rnGIc/l5c63JRBtwyE1DtotyvVxMhWggX70mlmnfpQLGfVu/uw6sfQ2bW4w8oSUtbXr31BVgUQ9IXJTuNWr4WKqzRBADMEDz4Ylt2OBDePrsRWpRAI7ok443NcD2BZAo3ZrR8EPMwwDS4H3JH/7AyKRS1TPevXbL4XJd4I9HqevY5U4nhySNqj+IcrxAzmNrYxDvjNVcuYaofpwIJFULvkqrH+jyfSPzJM6yWFCBmWLSZlbHXvwNHm6piIFREAPtFWhd1xnVF08pKUwJF7oKhnNaMmNwDMJzUQdJTTTeM17V4yC6gHKnbBPUDQ7+ChWNq27/pd67fHaKWazETWLpNKlzcBBgs4xwniFOKACjqcunq1JEyaFmL/2TLE6JiAN6No8FP4C7pcM3w0Zwe5E2lvVBn9WKfTmp4V9nGIPDi6EbHOcArJso0vYikVRO4zP//F5rjRFwCtUNBGi3h8tqRXfdrz71wkAQkAYc2afRYJeng1gNo+ewOEe3JndySGhEjvB3BDiVrPXYyC2KR3wgJFgsoPXt5QDSVeol4fY2EOiV12Af8SdqCuhfgH1F5smh8bPpIRd44+ky1IjjfXv3cm+xxaMPj0Sa06L6DkRorfi5i9TjFRsUm+gndY3mJUmKzbIj3g==
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
    type: Opaque
