apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgBjYE/VDvx7eJrJaw8kq6edfmegfHd+bZUTzaSZ5gsgNcwESd7fubVrqc/HwVIcVp0VlWtussIzVBcEpS08pWjshacPXA4ZJ65hzi4N5gdmp3RQ0k274X6StSB/8otD6RjVVCYu3zFg1RvjggHVK21WgEJakYzj3ijhe+uFTUdCJQPM3AYcunr3Xz5rrEXOPRzwc99zE9t1PVBJuL/DTaV5Er3zQe+WfHmt/Xf60auN0EckeSEJWkt0rICVzK2OzLaXcDoI0/QZEkvvPFp35xGc63N7SkvJKNPn0dsu5VPRS9aQk5KIFgBvdCSW2iS3VPnJlVx8BLHRjOrC7SDF/Op1MM8mdrtIXr/oPPr0dk3VR2M0X+is7gIvlsSbT2Ig3U82baVbfqUWF3dHU9Cc15T6kMeA3wcXWoAHueyPfGc7M/rK0ySPsF1+1Z4/DtKyI+3YhPV/AnxUuQ95jlcV8eM3pu+xLXyGqjfkYbS415WBn3Y/qH4PQlFXiDMQQrPg0K0SH3DAKedic0KF1UOw6ZhpdCH258/kOVU6O7J16UH7NTcHpXSt+SG1NkRfdd/ldrPxLaJVMI06a5avz4epltEDgtifzEMHG7SXy9B/gKaSkinIKT2Q2CogVG1ZfpKBCZiS0JjQV17HuYK58sCggVAWNX8YCN4qGZ07z8MBz3KYWdMTnMiySRcgU4jdGorDhV1g96Xeu0DX3OtCmcKos01m4zuN
    username: AgBNqyn0/9ucOBRxrxmt/xjKXb2c0xrPnBXRImgxrQAwRLBHli7Zqjtnx6m8gLp3OSM4UgxNSrADW4f+uvT/Nmg2BaRveAxVGHuV5/xnYnMBr8bvCkgPNMOWXHIt02fKeBbBPYEVmBHZZZAjiEFxpVohXvc//y7cwTLJc0jYfKj/WtI76DyVXhKyCE17RsSppYkEIQUUYL6LAsPRn/WImxO7EslY46CJmtCzwfj6PJdZLM6a2XOKI49NJEIOj2YJEBgT494nmrNiX9lWUyiM9gFfaBAXWkarc8/3BVsmdwH2wwyWHfLxuv73qVwZWsSWgl3ct8scMiBGkefj+eyPB1XHOuIaaq7kk3PHNn4YEziu7HYVMfmIa04GJUxeJgb6skhIQJfv0Iwk4UBDg9xInbQoYERKJ2IBHoH+ift4imMpzqwm15RgFwVxQd4egFqgGzWREZLbeX/446UVRxmKWpo+2XV2sg0eJLhK8PHX5FM6UrGRPADWPscSQE9mt1MwX0Rj5z/79n95mXQQK6Kk4LgCho0M75YAYeu93baM07eqRMBn78ksBL9IACmTEeOVdYSFhcTPMG5sJT1YM5nbWEaiNMFukwsQc3Ga+IFD6L6Ik4iY+v4CY05ehbxOJq2JtcJ3xiry30iHnNDMhOc9ItymlRjKhD1SgDsrdJWb+L0fNJab6zzaXPP0VXl0/TQi5myyCZkigeocprfURA==
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
    type: Opaque
