apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgCMl1Z890z+QVugZyYeAouSz2YPUWEmI8mqufkmbQHFn7pk5ERFam0e2iD5TygbGeqkDzCDELt2MEms1LEW7G/eHWnAytBtBUPwZPm6MNcrB/MjuhWvP4sOEntcyndezVtVXR7lUvqN6HPQDAFHV1QlLrVckLvrQzNk7inl6dRlJ+lRDV4xXBY7diHYI7TcH4awLH/RjjP9PILWpwhJAHwRVS1kQxb9EW8ebr2fEdMRRXfpKx8SmLNHKhXRHfXWKWea3/0Gc6cOAHkG1vtEg+1j9ECAF8bGy1cUg4OtjqTDo34RdIF2WR3n2zBJBpFHruCpNlskcBxjW9BlPXSoH30Yseh4R2BSbMR1obXZQPgiuYVSMajR7hd2y2UgE1C4jQl+kj4iVOkwAWjDXumzf48ejXJe1Wxqn+yAxzs+F60YIall8UUsGuCSq850EwMeUpV2zwuSe27f8Xb5Uhk5NuD5BnM3Sg06Fx2G2lAYlv5PIUSFwlKoTEJ6nt7+9RJB5KJA1htlLqMTlI5aXCICLhNUw0VJLccYHOVv1P0dxzoD0D51rL144ZsV4Vk0NK0oVMhBW3nGCN4GJb5iRLMuoHiQe3cfjetldSUiIvSNhaJtEXEuxyJncdhqjBf8Uq3Zn7kr6R2al53nzqh3WRre+zg2YBnpnvn962iclX6wrhN+G16zCsYO4q2KVMdFtDRTtN4FwF5QJzYP+79dclhWvj1RCkm/JB3jjdVf7N1nfPu6yMgnbfpUA7rC
    username: AgAs5u3Mzkc1L3LJoRD0JNhlcnke8Ho5YjaQYX4NOTNn1ogJT4ZVUaCvNCRlk4hGedJOal7rKm8mcTB+9kVH4a1IsvJcHDdSnU85th7p2U+XMeirES0LJ0kRZw60JnpH3wG9E8aqqExkJkICbmf5mIWKxYPE8gmN5KEkM9YAE5VjKv7U8Xi0nUod/GrWMHJGRr2RmuqlrAUU6/xGKI85ut4yPopYjBCsNGncwBpJVyLQFzzBWLYtA7z/2/WGyMX2Tx06WcceOxFj611ZMqfvMHp4aOa1JnzyjfZH3y7Tpr1hxSPfRR+2AqTxg4in0NXkF2qGs2bJdxEQINk6ydn8Ybhh2QqpTUcJicOI/5f8okH5LyAGrBbExKFWOOOF9w7CaKTOWvW74Bs4A9SmNQWZevxHblo4PJXzeH32G5i2MOHJm3/qKdOnkQnlLEHaQHIPdLfFEE7yan2q61AGgwSHEM9GeoMkJkuRZP7t0YgjT9s95tVI2xKGSor+zyVm58mBaMJuAMHtP8iimYBnOfE2PE9QOHlqxEhNkXgCPgdLWajxLkOP+qYQDe7GdMsPYjbdk66s3efhqJgYCvPZy8gYGyFGveavmCBHV3CavvvxrKmu5CWbopGs7xk/KrjcwgUzwHV4/4WOaSpBoW6ANiXg5ljVKxXY1F3RB1yaPfDKWcA/fDsJQW3lQnOPsz8Cl1xn415REWyMWxpLresBTw==
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
    type: Opaque
