apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anime-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Ti
  volumeName: anime-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: anime-pv
spec:
  storageClassName: manual
  capacity:
    storage: 3Ti
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.4
    path: "/mnt/default/anime"
  mountOptions:
    - nfsvers=4.2
  claimRef: 
    name: anime-pvc
    namespace: {{ .Release.Namespace }}