apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  volumeName: books-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: books-pv
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.4
    path: "/mnt/default/books"
  mountOptions:
    - nfsvers=4.2
  claimRef: 
    name: books-pvc
    namespace: {{ .Release.Namespace }}