apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: books-pv
spec:
  capacity:
    storage: 3Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  claimRef:
    name: books-pv