apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: config-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.4
    path: "/mnt/default/config"
  mountOptions:
    - nfsvers=4.2
  claimRef: 
    name: config-pvc
    namespace: {{ .Release.Namespace }}