apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Ti
  volumeName: movies-pv
