apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbit-config-pvc
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
