apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-ingress
spec:
  tls:
  - hosts:
      - qbit.simonmalm.com
    secretName: simonmalm-com-tls
  rules:
  - host: qbit.simonmalm.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qbittorrent-service
            port:
              number: 8080
