apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: software-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: software-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: software-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Ti
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.4
    path: "/mnt/default/software"
  mountOptions:
    - nfsvers=4.2
