apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: software-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: software-pv
