apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrents-pvc
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: torrents-pv
