gitea:
  gitea:
    ## @param gitea.admin.username Username for the Gitea admin user
    ## @param gitea.admin.existingSecret Use an existing secret to store admin user credentials
    ## @param gitea.admin.password Password for the Gitea admin user
    ## @param gitea.admin.email Email for the Gitea admin user
    admin:
      existingSecret: gitea-admin-secret

    config:
      server:
        domain:
        ROOT_URL: https://gitea.simonmalm.com

  ## @section Memcached
  #
  ## @param memcached.enabled Memcached is loaded as a dependency from [Bitnami](https://github.com/bitnami/charts/tree/master/bitnami/memcached) if enabled in the values. Complete Configuration can be taken from their website.
  ## @param memcached.service.port Port for Memcached
  memcached:
    enabled: true
    service:
      port: 11211

  ## @section PostgreSQL
  #
  ## @param postgresql.enabled Enable PostgreSQL
  ## @param postgresql.global.postgresql.postgresqlDatabase PostgreSQL database (overrides postgresqlDatabase)
  ## @param postgresql.global.postgresql.postgresqlUsername PostgreSQL username (overrides postgresqlUsername)
  ## @param postgresql.global.postgresql.postgresqlPassword PostgreSQL admin password (overrides postgresqlPassword)
  ## @param postgresql.global.postgresql.servicePort PostgreSQL port (overrides service.port)
  ## @param postgresql.persistence.size PVC Storage Request for PostgreSQL volume
  postgresql:
    enabled: true
    global:
      postgresql:
        postgresqlDatabase: gitea
        postgresqlUsername: gitea
        postgresqlPassword: gitea
        servicePort: 5432
    persistence:
      size: 10Gi

  persistence:
    enabled: true
    existingClaim: gitea-pvc
