harbor:
  externalURL: https://harbor.simonmalm.com
  expose:
    type: clusterIP
    tls: 
      enabled: false
  jobservice:
    replicas: 1
    revisionHistoryLimit: 1
  notary:
    server: 
      automountServiceAccountToken: true