{{- /*
 apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nextcloud.simonmalm.com`)
      kind: Rule
      services:
        - name: gitea-http
          port: 3000
    - match: Host(`nextcloud.local.simonmalm.com`)
      kind: Rule
      services:
        - name: gitea-http
          port: 3000

  tls:
    secretName: simonmalm-com-tls
 
*/ -}}