apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: nextcloud-config-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config-pv
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.4
    path: "/mnt/default/nextcloud-config"
  mountOptions:
    - nfsvers=4.2
