apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secret
  namespace: nextcloud
spec:
  encryptedData:
    password: AgAHP//vfAT3N/7fzxrVfmzb+6ZB9jw7Hx+8MIolz0HrWagrMjizgonR2NIaIuog6TOrTE5zd1JRw2A1oo3eNeaYLseNYSvnW4V294fn0xzRKHEAlq69DBqhTlW57FtdvFDFqwhAAPGQoiEkv7xs+usau1JJBoB57mYHnf+3/BA7RHqkM3a00tR6bBsdNOv0qlb+4W3ustvD9gPhsCpAu7U8yDYE81pqnIYMbr6xMZkl/JeGKYx1Cdcx73Y1y7TuIU28DYLMrX8Ait98sO1B3x75P3um/sAunqWtKvnR16b1aPKwSGpgINJaSz/hZL3yoDxeoqqkvxb/A3S60OLWWNaDgs7jzRk1q7M6/dGG1fW9zdWXytsQtj73opDV73YqDe9rnvKUkGQF9IspVw6MLwtNRMF3lrdDyf/akZ/2/DlxcfeJFweqGs64enzgw4Om5l3Uk+VI0dmxqjQthePU+xqOljnPd7w5aWW8M0T+5gb++9jI//BI4vPizhaa3+D7eespwtog3WmNBRvGKQ7eSuvJZ8n+/mOTAcTFC7DUBIxQgeXmUNYpOc8Wb33QdCXmLJ5n/a8noLY0tmcVSA3Z6iNlzvdZbOrnmPBRtsHYDmP1aqiY8juDDFQqXGZ/9IMGYgW3Lt8/oXge7iw/W1HGPI3aHFERInGdEE6qzpWRvXPe5IZbcZ3PZ3RqkZi+/VtP6T8SgMSEWrVEPDEafLQv7sOAIEnA6Ebs
    username: AgBCEFup0KYzx8pKHRSe8ymZXjzpNpq6svj2XGQB5zkYcCP2Uz9emKrfUTDVvAtDAGFEFY21R6CDc6B7Wl5elkp/aipgD1HuzA6OqDGuNUJ3uhLnEUOG44vpfSknOU19oBvWkxFUYF8JegIvrd6pyMCvUI2qe5W6kG2xWTolgEjfYkbNyn6cFxaEzhWfX5+lFpvdh9ehoJIovujvL8YloGACRgRpu5WrbSBU2iO8IWYJVShfp+cO6dic4TBAifVjFr3GnKJr9yKRdUOihXHGRBeb4Asds41R2MnHCgof7kiOD02QRZC2V01ErT1D91ktyAiYnrAD6WPYFUV7q2q717oW8WMjWuaYy8Fs7QWXvmr7cr06KvQJrkvo3IDbBzivLw9q/lfe6LoFvdZbZiB64zliqh6qFnwkesM6EvHEkjsBZT+/Ay9xCJDPPRa4klc37N8L9EAxJ98KTCTL5RBc82Hws4670JiyuprcTofaZITUnOFFJEbhdqp1EpcpXLAHeMQAgGG0KphEvHQSxn4fPkCkP1T7YzloQnpGHnjR3JuN5jpt7GVyF1DJXTYgCAwAsEeuXt5Sqj1YD9abToYsNgHC/76D/lGuss9Lg9jifeevtCeRaayTmSlZ6f2u/wJbqhvl43cmW0ZDF8GSodx6rgvvkfn+VDjo8m+OgLHmMuR2uR6FCuvoHd5FibP+g2nD3xSFw1FK3jSo
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secret
      namespace: nextcloud
    type: Opaque
