apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secret
  namespace: nextcloud
spec:
  encryptedData:
    username: AgAdex39Hs66ZQ3X3PbxsvygtGHy81BZZIlSsqgIGPyaoOZWEDp0t1TLliEoOCd/SmXJjohycs5BqFl61MfnMUWTRBd1SMVG6heDU4dl3sCseVRrMCOwgi26Dd3gDHvlUAem3TEEcRChyleuv44ez8LFoHPJtKAM2n3ICnXzo2dC5ne+mAUYXyT7KVTMaOqnmRBSJqMdQefSpoVZwIQLJ93L0b7NvxWn9HxJEuyxrpsi6BFUBdj/ejRT0KjNG6dI9fdtl6OY2M+Z8UH2NgCKeEtXBFE88LKB64UN2DrF9xxXASjqouZK9YWAsvRe3k1FnHm5Jo+jkTu/JANLmd1V6v1nhIIgl4AZS7wzauEr70Oqwkl/5SyhHX7h4nxY9gZ0s2U5wBoA0px3uYpzx9kAizn7jmqZ4ExuAM2t7ngoG8RwtsdZ/ZNHOrGkkbXReTOsq4DvRoSj7euslqUYmO2ABPLzSbkpA9ggySXM105cySNYC0yuWVjHaNRV5xngm3xKeKmpxxUowme6oEq7xVEK/FkMcOTNRBMP96qVwt144/e2XpFBCgtioF4sprEtIqkzwecGBWO2LW2TIXym80JQbOiXykFHT4aSw/0dTnXUSOoIg4qFaR5G2gAQs7WWgGuAwiVqtBuL1w0HOJJzPuT4saIFQwJkA947S017ZEiZUk69fy6EcqK2QM/C3rOpT/j8aS+UkzO3mcY=
    password: AgCn5jTuDypdh0UauUAvQbwU+7P8CoIEEfkAukK+XF2l2YRPHmvxP2X5VMeMimgZYfvu7YoK8umS351aYqZk6tEVHGqjsMbePy02yswMxBer6sbCWOlPhRfV9QIZ06gq7u3AkNGc/gaKfHbqca+8SFZg9I09KHWmMZb60PISDmHurmg+oFZ1XoDdCgXe65vq5Rl5y4C/Y4LW54uIOCB3zfXu/veHcWYU6nljbpAXQTNR8dd/NYTtqkFZaHqgMqvv97fF3UhruSuvlNmueugRY/mDWOoKZTn2AEHbd6DxqfBpQ+ooyK9BXAgCgHGfW927Uc7wLlbjSwPSIgHbmFvqz6eBhKHFxxZYt2Oi1WrZqfKcJxPJYUThohXc6/avW/e/t4X6Qw395fr8iMTsOA/tZaCADrngpB9bUh/9YO91B/gTrLS8RdJeh1Y47NGQUism+Dzrv3INe0tSN5iKna8tXJqSAdrhyhk+DnntyoZ5IRIqyJZOJ2hHK/W9sWlaU7z595L5XeDnxWSRc36PbYQ7WmQ3OngS9c3Rl2nZOTNvEzfMYxRMbqGkHeyiEh9GC4mGdQ/mr0xp+G9Q+XBBDh6GY2N5Jo8oXf6QWcPsvI88wnUgFTnjRgHQJleQRAkUYcb8v3RHWFekmAM8Ye7U3Uwmk7Wig/q2tZb9SA0KFOxX2M1Dwz15NW8nBIfnS/HHm0SAQeCd8ENMeTC6O3qPSHf5sCQ7wZFGERVh
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secret
      namespace: nextcloud
    type: Opaque
