apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-kube-runner
  namespace: drone
  labels:
    app.kubernetes.io/name: drone-kube-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drone-kube-runner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drone-kube-runner
    spec:
      containers:
        - name: runner
          image: drone/drone-runner-kube:latest
          ports:
            - containerPort: 3000
          env:
            - name: DRONE_RPC_HOST
              value: drone
            - name: DRONE_RPC_PROTO
              value: http
            - name: DRONE_RPC_SECRET
              value: c8dc739fc5de023e3c63243d8f5b36c2
            - name: DRONE_NAMESPACE_DEFAULT
              value: drone
            - name: DRONE_SECRET_PLUGIN_ENDPOINT
              value: 10.1.5.63:3000
            - name: DRONE_SECRET_PLUGIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: plugin-secret
                  key: SECRET_KEY
                  optional: false
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: drone
  name: drone
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - create
      - delete
      - list
      - watch
      - update

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone
  namespace: drone
subjects:
  - kind: ServiceAccount
    name: default
    namespace: drone
roleRef:
  kind: Role
  name: drone
  apiGroup: rbac.authorization.k8s.io
