apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: plugin-secret
  namespace: drone
stringData:
  SECRET_KEY: 58466c409b50f8a462172a368d5bfb50

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-secret-plugin
  namespace: drone
  labels:
    app.kubernetes.io/name: drone-secret-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-secret-plugin
  template:
    metadata:
      labels:
        app: drone-secret-plugin
    spec:
      containers:
        - name: plugin-secret
          image: drone/kubernetes-secrets:latest
          ports:
            - containerPort: 3000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: plugin-secret
                  key: SECRET_KEY
                  optional: false

---
apiVersion: v1
kind: Service
metadata:
  name: drone-secret
  namespace: drone
spec:
  selector:
    app.kubernetes.io/name: drone-secret-plugin
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
