apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      manager: argocd-server
      operation: Update
  name: services
  namespace: argocd
status: {}
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - name: "*"
      namespace: "*"
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://github.com/a19simma/homelab
