nextcloud:
  phpClientHttpsFix:
    enabled: true
    protocol: https
    
  nextcloud:
    host: nextcloud.simonmalm.com
    ## Use an existing secret
    existingSecret:
      enabled: false
      secretName: nextcloud-secret
      usernameKey: username
      passwordKey: password
      # tokenKey: nextcloud-token
      # smtpUsernameKey: smtp-username
      # smtpPasswordKey: smtp-password
      extraVolumes:
      #  - name: nfs
      #    nfs:
      #      server: "10.0.0.1"
      #      path: "/nextcloud_data"
      #      readOnly: false
      extraVolumeMounts:
      #  - name: nfs
      #    mountPath: "/legacy_data"
  persistence:
    # Nextcloud Data (/var/www/html)
    enabled: true
    storageClass: ceph-filesystem
    size: 100Gi
  nginx:
  ## You need to set an fpm version of the image for nextcloud if you want to use nginx!
    enabled: true
    image:
      repository: nginx
      tag: alpine
      pullPolicy: IfNotPresent

  livenessProbe:
    enabled: true
    initialDelaySeconds: 240
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 10
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 240
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 10
    successThreshold: 1
