nextcloud:
  image:
    repository: nextcloud
    flavor: fpm
    pullPolicy: IfNotPresent
  phpClientHttpsFix:
    enabled: true
    protocol: https
  nextcloud:
    host: nextcloud.simonmalm.com
    datadir: /data
    ## Use an existing secret
    existingSecret:
      enabled: true
      secretName: nextcloud-admin-secret
      usernameKey: username
      passwordKey: password
      # tokenKey: nextcloud-token
      # smtpUsernameKey: smtp-username
      # smtpPasswordKey: smtp-password
    custom.config.php: |-
      <?php
      $CONFIG = array (
        'overwriteprotocol' => 'https',
        'overwrite.cli.url' => 'https://nextcloud.simonmalm.com',
        'filelocking.enabled' => 'true',
        'loglevel' => '2',
        'enable_previews' => true,
        'trusted_domains' =>
           [
            'nextcloud',
            'nextcloud.simonmalm.com'
           ]
      );
    extraVolumes:
    #  - name: nfs
    #    nfs:
    #      server: "10.0.0.1"
    #      path: "/nextcloud_data"
    #      readOnly: false
    - name: torrents
      nfs:
        server: "192.168.1.4"
        path: "/mnt/default/torrents"
        readOnly: false
    - name: books
      nfs:
        server: "192.168.1.4"
        path: "/mnt/default/books"
        readOnly: false
    extraVolumeMounts:
    - name: torrents
      mountPath: "/nfs/torrents"
    - name: books
      mountPath: "/nfs/books"
    #  - name: nfs
    #    mountPath: "/legacy_data"
  persistence:
    # Nextcloud Data (/var/www/html)
    enabled: true
    storageClass: ceph-block
    size: 8Gi
    nextcloudData:
      enabled: true
      existingClaim: nextcloud-pvc
      accessMode: ReadWriteMany
      size: 3Ti
  nginx:
    ## You need to set an fpm version of the image for nextcloud if you want to use nginx!
    enabled: true

  livenessProbe:
    enabled: enable
    initialDelaySeconds: 180
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 10
    successThreshold: 1
  readinessProbe:
    enabled: enable
    initialDelaySeconds: 180
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 10
    successThreshold: 1
