apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  namespace: vault
  name: default
spec:
  # required configuration
  # address to the Vault server.
  address: http://vault:8200
