loki-stack:
  loki:
    readinessProbe:
      initialDelaySeconds: 120
    fullnameOverride: monitoring-stack-loki

kube-prometheus-stack:
  grafana:
    persistence:
      enabled: true
    admin:
      existingSecret: "grafana-admin-secret"