apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  volumeName: cache-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache-pv
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.4
    path: "/mnt/default/cache"
  mountOptions:
    - nfsvers=4.2
