apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shows-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Ti
  volumeName: shows-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shows-pv
spec:
  storageClassName: manual
  capacity:
    storage: 3Ti
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.4
    path: "/mnt/default/shows"
  mountOptions:
