nameOverride: ""
fullnameOverride: ""

jellyfin:
  replicaCount: 1
  image:
    repository: jellyfin/jellyfin
    tag: 10.7.7

qbittorrent:
  replicaCount: 1
  image:
    repository: lscr.io/linuxserver/qbittorrent
    tag: latest
