apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgDNYAR3Q4U3EeDZx9tfI7jNhaP/canrbzgF9Oq8u/9GmEMnKPaBHZIfi8+9DFlV0BmX6W/TZ3WTi+e6gBXfkc1CPl5ywgBqB0jadozrmMzMKlq4KVkRn9lPLABxPut3s5OVKq38Ysp484buf5/OWord87aw2zviDYvar6iDzrDOuWNI+hvew3rCPxgEW+2rz0n3NlvUVAZBbiADL2cQVdISCrWhRjeVYAULHcfkRaNLG2kW8gtCTcq2gjMIlu/564VdZQtptvQjvCoMxx0f8EU6v5Y/uWm6bq0oDQbXJeVxFzGDhleFyHE8puK2P2GGz7VHjIFnnyNtc4yvxmdDPLxo1WOn9qodiCcFLcogaDcBlEdcECbOpfvPQPR/69l2aK+3fNQYsKvbOg1bUue4xJc86LIj4vgvMdIUF/m372jwwR9+zb548T9fUZ738XsDM0KQE9+7U9mIJZbvkf4eGQaiEr3kmAZIwhy3zde2Y6HtcF0wuEa8AC2rKvAa7DU5GQPNpOnVKb5dkPcV2nFwl4kV2U7BUqIykx0tq53UFPfELlVadqfvE9R69q5z9PIVBTFRaUOoesmt16GiakqC5HrgVqRJRTH3uCw9YZ4Mdxa5cp1qpSGT6rr8ihupG5fmtmUSca4aSyruiIO1SCXG0TfxdR2Csl7ZceoGrhs7P2yXDIejZw5f/SeOUv3VhzTwk1S1Zjno9LdkuaYGu0fYavPQWL9geWveonh1GLcrS60FtXWl0tZqjsFU
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
