apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgAvHCg7iw1ysj3LNQEMGJzdMJfIjEVfG/3dr0NiAg3N/U4I6qBFLY2FRMQ0XUwD+YeIalCnw87V6OZSOUH0vIpNu+Mof9dy+gLLpAqT8V3TO8VHiK4MTBD95Q/UyLIBdBBEx1Ff0TVhHwRNZqPnxcMdvcztHWa959VKmjssIPaBTNjZB153n+YmQ556L4ncULvLF/iL/jcWr3GDv6BdjzNYv2s4GsQmVDv4S3OAM8mntCfmJ7Vzcjb/so7ekmEKoIPsc4hQQ05bubej6Z8eE5M13ke/YYZP7C9wCWSciZ6QCqSVf78ntJqN1RQyUlH2FZA1ktg11zHr6tamX7ezFArw0FJftPNcsXSzDr2Cy5mt3mIOgs6kpC+Nt2ozGRx1Mkpb8Xdtsc/xbPVL4cWTT+26hDTOkPvT7YpNVRFijoQLfzq1SJpolr1JpzWuuquC3m7XpKFzhKfSKOij6jnlNuTl1/vNk3sW1K4cYoe49ZAN93P4zcVTDPxfJ4zyG9TbkqOlEdTvcJoo8QwOP9TBjFGmRiqNtEHDlUnvU+LZd5NL5KxBAnJiR/HkUgfUKruwgOZKJWpzGd17TDVisbwZ1n15hjSD1rAjNLZWRyEdST4JffqHP9zfpN2gzV/WnKh3ERYjAYjnRjKDFLW/kmWGvY5ukbxdQM5SkxfQ3lqY9bC3waC3s9u+m81goKcx8Gb4BTQQiRD4kqSZaGWlzCihSaGh84GqYMwp9bBiSZSvDR4Rq6EVMNpSGXEx
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
