apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgCkP8CHb466CccP0y4K2a3m86KX4AGB+xtJBS6c0sNC9D9g7CY2Q56BUAjsfs8jPLC19je3snPlv+FyfiX0crQrYj2zEeKOGUPhlcq13MMZSzE8EiSx2SEb3dvJojBaw34bYRYH8aM8bYmGUGW4NLMYl9/S2ND/DQIU7F/C8b0g+TE3EkYV9ZpjmR58bj5N+wx5/tKKTqQhEjOkA71Aa9UbWzEpsWlNHHb7KaKlva2BEsK9Bqb3scPgYo24n9hH4t68JfEvRyn9C4v6s+o9Zo/U/WmpfLlteE8bq+LvpGc+eL9fEp/pgRKR+DL0R6QE2fhvMXVZDYDYZc+Ldlftb/54BZKxAq/1+ZTLKLc+yEiRQ8Q+xE6i/U8ROx0v157ymhgqzZ4b43gUhL6z1ickQCElioCoORx9VNiWeqOSijbwHZa1vZdD/Xp/j24GuFii4EiSWNWwY6OmyMaC5M9EIUs9KZUTLYb3ujSmvftIlRNlWHk7bG8xXjF64RsVbo4zWPmnIj2IqdhovwkGBDiIXhCqCXKiuXsvM5fTMXCRK5QmckwvKBGD14uTdOYfCxuNOXeSlAm0+ZpA2WuZjWpYBAwaaU7RIpSdNEUYxesjwY7jXlJaGAm2HAnUqlbKXQ2h8GuylqM/jaq1dPhJa0abjecC/wT9e5i+EpybUDALYPxfXL7+t5RsnmWFIfzpqipAwg1QDLfVW+lOWGKQA2CTNW6JW4X0Aw6snpN2gTAxK5rOni1KFGrySAEt
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
