apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgCZ6jA3q79nEbfM0mRP960PlWIu97vRBqJmZA3DiW0nVU7DMcryqcMy5Jt6C0yPD927jJgArEEuWSR8TV+Jebmmrb+I7ibSHfTTqeZ9rzD2WgUsAoy/ztebcGj5pDCu85Rfkcqkt8F+mNJ66/OH16VFFVY0K6fmraUKxE7GZSGWVAbzUlFDeZ3APifKxzBQCtiw+jOqOZbPmQNPzYMiZU52IcZSRDtZf4UYIfY47TKBbwFvcV/S/DIbYkCUtwLQuFjr8ZHEicQk+gU9156hCKOT4A3Fuwwyad/6FzB+NUgu+Joui+BlYSTXBmUVDf/KKlEmC8Eivu95Q2L4nlvv/4RUCYBOFpwLvvQpw/WkFeiduzJXmQpQMvT/kArqi3JSYKai1wQFExPr3p4a+3Emn3OiwmwfXCs1TZv7Z4mqOgnF3aKN8g9i3I/PYC5E+Ocuzze9jZJPpq1TMr2IJghmYWGqOZd6JzOM9tW6Fqr8gyDnn8utRuziI/r8mtpVDEW+mlm3BxHfcybNRiyUvgntsJjlmNNUNHN3r0OJ5BvuOY6S+hhjhzQ6HChRiHUaxXjOmktRj+cDHqZozMifuc9E1uiDpDGY8CTi/O54ndwKZwhWRbXBGLWpWVWrse3U/aj2k0teP14fagt3xfB/XaTtk9ADXxn0zSI/IfWoLE83bN04gdeX1eq5wzc53E9W3rdQLt+uQhvl4p+Wma3WHfhYTIJCXAdoLBA6VGYRnh2iwMmxaIwofzEU
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
