apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgBnGfhxXrVMG6/aiSPCbJbi/Uv2XYIFGwU+/s5ZVjVrtzj4LUqK6qCdFqNRN05KgONjLtvdwOjRvTRZW1IzlBPPEoIJ/kmzwqEDv+Hg62ZRCViEIZHTJJIm3UrL3Z7h8lmCi/ND7oYCH4bRk1uJxriDJvX9TOH1TNjQykVDSlTZAqdevBzYiIeAW7qtEqwz6M3l4/NNXk4zoWDyywOf+3XIYMPKLORHc2p2TwSPRboZ2PgXs/PcDeaQIxtmnu2JQq0BYf+30vkfNjF8UQPsjxWq7SDLwdfogaArOuKHs572jsu1Z1en48WitfyM5llDuf7H85vOyZtFuLoMTFQ7LYrtX0Ng2zAOsYovyRinFHw58HA4bmiERC6GVpLQKH56saLMmA7Zf2hyVVbxtdN9K5qRfw4VjyzaR71cpj/EtaB+5QjtglEdrmlJ8rzXjI7JKp1os37ZqIXLeNjguINbJrGFmfTTKLycVAjCVcls8b54fFpDB5asihTUcOoARM6n+vTAT46d2/r25MKLh7ZnuCYsvJVW04tHlwUW1V/2qT+wmLR4KFSXz6pc9tJid11Z6SsjjobylxeLYmEtbgjO7NZABNGiqoWPXoxsY9htjpgw9u1avLB8W0GBkkt3uQLoIP7SMlL7gQHmb+ilCRdOENGLnOOwEJVhq+ZGbmSdsusVkBlP9SBjLOBB63vT2AdwBkWT3jE8gh8z19Swh5kn8zdrziQsY8ghQw7jA3kLt6kzM6oHW+dF
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
