---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: simon.studet@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: simon.studet@gmail.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "simonmalm.com"
---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-production-http01
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     privateKeySecretRef:
#       name: letsencrypt-production-http01
#   spec:
#       solvers:
#       - http01:
#           ingress:
#             class: traefik
#             ingressTemplate:
#               metadata:
#                 annotations:
#                   traefik.ingress.kubernetes.io/router.tls: "true"
#                   traefik.ingress.kubernetes.io/router.entrypoints: "websecure"