---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: simonmalm-com
  namespace: default
spec:
  secretName: simonmalm-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.simonmalm.com"
  dnsNames:
    - "simonmalm.com"
    - "*.simonmalm.com"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-simonmalm-com
  namespace: media-library
spec:
  secretName: jellyfin-simonmalm-com
  issuerRef:
    name: letsencrypt-production-http01
    kind: ClusterIssuer
  commonName: "jellyfin.simonmalm.com"
  dnsNames:
    - "jellyfin.simonmalm.com"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-simonmalm-com
  namespace: nextcloud
spec:
  secretName: nextcloud-simonmalm-com
  issuerRef:
    name: letsencrypt-production-http01
    kind: ClusterIssuer
  commonName: "nextcloud.simonmalm.com"
  dnsNames:
    - "nextcloud.simonmalm.com"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-simonmalm-com
  namespace: harbor
spec:
  secretName: harbor-simonmalm-com
  issuerRef:
    name: letsencrypt-production-http01
    kind: ClusterIssuer
  commonName: "harbor.simonmalm.com"
  dnsNames:
    - "harbor.simonmalm.com"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-simonmalm-com
  namespace: gitea
spec:
  secretName: gitea-simonmalm-com
  issuerRef:
    name: letsencrypt-production-http01
    kind: ClusterIssuer
  commonName: "gitea.simonmalm.com"
  dnsNames:
    - "gitea.simonmalm.com"