---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: simonmalm-com
  namespace: default
spec:
  secretName: simonmalm-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.simonmalm.com"
  dnsNames:
    - "simonmalm.com"
    - "*.simonmalm.com"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: simonmalm-com-http01
  namespace: default
spec:
  secretName: simonmalm-com-http01
  issuerRef:
    name: letsencrypt-staging-http01
    kind: ClusterIssuer
  commonName: "jellyfin.simonmalm.com"
  dnsNames:
    - "jellyfin.simonmalm.com"
