apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-user: AgAg61W4iEmPqmSpwZ00CXKaJnmAv+3CX7jYOR9wUQtEa8jC27EtdJvMCLrmXqY8urjbC7uWpPnxY5ZHWHmrRuEzXZpXsOhgAwwiHXCvvQmOdl+OweOQIzBEBoSJ5oiulbnWmwuEF5HO4VsNlVyHhQWR5U3pBvjc7t+POlWkFvC0utXlEUO2UsLGHbI/PogjG6j66drbTO57qBc1soPsl6R1JeeYrbtYYl3hTkvOh4olUVDIpz3eX/QFC0X9KXMGbLGm/WIsSy6cPULPMcDeVobCyw7xO142mw4dkVrvXViOlAlLrHBtQA68d/GFGwHLNvG28uxdKOcxO7AMSCRFqRPvzYcBqddPLfj7Px1aNRBFVg8sh3qyWR2M6zsUlymnRYIv6BJDjWFCsI7v9R3ZaMhBZfE6fsTwP1cId8ZK8k6qQTX1GzdOe2w1Gj4duI8xb5Y1H3S2mJ0symiVwVNOC2DRrErnP2MdU2DWPFOKrN8QGUQAhlmWy6BPn5gThjWOB/y7608K2gD0GJIrfog9ZDzy3MjHFhAQGfRRjFOQgOKIH3Znj0T/NF0FIPpzANUxwsLx0vPQ9rEdPIZxnDWb6CBLdpcTz6yWQT9ZEA99tQejTaOspPjuu7kMNF+DnQ2YdKL+jUWPxi6jbxlIyc5D+G/7SVq3wsZlaVWxmIZH2Obiz8Nx9waoTp8TCAiHTpMeoZdeZb3CGA==
    admin-password: AgAdAQN0leDCWRTfDrFQwcSkooN1zJzJvTKVO15mpdJjS6/llUcOIS2Ra1AdeIrjvhqwH/31dceaexOexJSVgazElEeYmQXoLmwAJahOSM7R5yLITBlUsrPlMje4/Bxw+th3sJ7YMW0hFRgESnDupECwDtRuILzhq+JlCTThjqSBkDGIhjvRpYRWvN762YGRwis/ywZkbGc3oLql1xF2+nrBsS1N5u8GFW2vWt4tcTHxxQRffyh5pqa+nPIOVi2w6mpXIVlyUwxEI4tRxQ+m99Hzp8Tilyw/uepujHrhLv+WgcLlHVSzqgB93PWB7Pc/eBW3P1+nk1emvQC7WGvGZG7aLd3GjEGGva/eWSWfjyX5/ICVN4C0NQRZUbd1qPr4zYFjTyeuwYP17thC/X6mpkw9Rh0n9/S95YltxMESL0iEQt99bYrs3l7HUTBhMgyjck3VaP0E78rrvnmOcZ8BmBf54FOc8IYbyVQa99kv/V8SOmIWMMql7yRYTgmZYKEjno+yCO6NdsUiwDPH3GVgDxemqtkR43AWrIg6gkTs3z3z/Hwf7vtVqimdV4nbtOm3i6IjmHH4INmfth7SVOxR969TTnD/k8wb91X5ZGAlUdSYBqfuXoh27q7OKptXXI9MYd0WUAHV86RSej4fsClzvWcZbCF044nl6sfvVtollkNDkaZzSNe4Y55hg+tblVDFUL/WrXFz6AiUb+wL5ETH0hHrk5scpw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
