apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAM80hC1Jlc+6yaDuhvOrCRzLY3nsOJNbgVEKlhIsttSw9RUYZClIeKDxYG29k3vkADW5yL61nEytjNPWnhu5sFresIevouzsglQyeyGT8X/A/N46f+uaHCU/z4AYbkY1ts1/ZKl4V+HIE2vltAalwVGXxtSm+TC9gz17ye2KUiE4IJBQSs1FDRTWyiZJkyxvFKR4RYcLoh6w9opp8i0FlHzKmQIBwx2dKFc8ODzwnieqNrLd4hejtrlBWK4/ST39hv25P1zJw/iZUts6vFA51oEhDilLEcsz74SYwVZv9wCEk/pcnv5oWYW4FsOGX+DGL/id1TGFjLO1TJ1Djq1lsLD0TaeBx4pOvOAsbp0/jSuGHpSkXxNn9QJISpoJPdWj/9pKfDLuJDq8ROT+xxl5sEFQvofW64+np0OrSzACX9L7psDJ6XI90S8WNw+NjZxnGxU/PVF5WQaZZ20vunBX/rJ4SOqsfQ/FhqQ0N6Ft3/CEWI7E4h5RrZY7nvG7Qs4HVHlLbUbE9QMs2krRc0N4fBost27gwWvzQkRymQVNDRGuQItSQSgkf49zWje0NI2FNw0xRYu1DLo7dTnW2S+uNHbDHl3nldFVK+t+nja0sLl0dB+GoTAvITP5td6Fy1LvnJ+0YcUUceia+lO7hD2vy0CsqTtioNGtIVkekbwkeYnJtWV9OFViCIG6XoU4+/pv+q9/LkUs6VG81grFp/kiAXDwTP
    admin-user: AgBt+wYyAJzBdlXSqYSO9ugQ/glV5mD5m1j4krCmjTgVeCvG6v0FvagxvLm/6Q4TADT5OAB0DVk93qvTiovfnAehHHIP3ROGy6g+TzZF9Z6JaojDtubncwi0VToUmtS1fS6egx89JmV2R/3E4EZOzY/EaB7s12uUq+YX4MMZesZdLDPDvWq+FBqc1hYCqRI7mN9/N6AExVhawl6mHrjDv1dUd+mYgQgA4BQ5RnqD0ccwP6dQG7bz54J+BVQx/JArxMCWz1jMbAxvazawPglU7HKynh9oAxMyTty5Tmf5rT4rFmwoDKYJH7eeJ/N1VxBWaFvs1mgmdSli150nEPuNfM3kjYf/rgwuXz98OQo0kKBfPJPc6G6m5me6l5cAM2YEKQSfh7fTqOlkXRbBKE/7/xtoGDsA4pf/zN+MV5u8NN063GktL5A0yoF1BQXAvkSHPMGAi8ttc290e8kwq86z4ac2W7xxPiRvhh/cRMDY29iEzRpcTZFnsTci8AOLlekyiQ0mleM9TNmZCa/qU6ManI3MNSHtHD/kyYXkskByDQbglGVkNzs62KTyCVwWgL+Zm9X99yzhmGIg7jFAVDkQ7pn/op9DJ6Z9JmFE5WFhFseFFvs0KFx5cTuoixJT3XkMhotF51JdEFR1+WZxGOmRxTDTlu7rqjR1qFQJ5IQA05Af7oRMR7ooaOkmMVHGEdcYdULhOxvp/w==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
