apiVersion: v1
kind: Secret
metadata:
   name: restic-config-a
type: Opaque
stringData:
   # The repository url with pvc-a-backup as the subpath under the restic-repo bucket
   RESTIC_REPOSITORY: s3:http://minio.minio.svc.cluster.local:9000/restic-repo/pvc-a-backup
   # The repository encryption key
   RESTIC_PASSWORD: my-secure-restic-password-pvc-a
   # ENV vars specific to the back end
   # https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
   AWS_ACCESS_KEY_ID: access
   AWS_SECRET_ACCESS_KEY: password